### ISSUE TITLE
Database conversion from 1.5 to 1.6 failing

### ISSUE THREAD

**Issue by PascalLesage** [GreenDelta/olca-app#16] opened 2017-04-10 19:14 UTC
Some database conversions are failing. This is due to the inability of the conversion to "Update to database schema v6" (Subtask of the "Creation of data quality system"). In fact, in the openLCA Update Manager window, it is impossible to select the "Update to database schema v6" option.
This results in 2 unexpected errors: 
- failed to add model elements DQ_SYSTEM
- failed to execute query: select id, ref id, name, description, version, last_change, f_category from tbl_dq_systems where f_category is null

**Comment by msrocka** [comment] 2017-04-21 14:01
@PascalLesage many thanks for posting this issue. I can reproduce this when importing the [openLCA LCIA method pack](http://www.openlca.org/wp-content/uploads/2017/02/openlca_lcia_methods_1_5_6.zolca) for openLCA 1.5 into an openLCA 1.6.2 database. But there are probably more cases where this fails.

Here is the stack trace:

```
ERROR - failed to execute query: select id,ref_id,name,description,version,last_change,f_category from tbl_dq_systems
Table/View 'TBL_DQ_SYSTEMS' does not exist.
java.sql.SQLSyntaxErrorException: Table/View 'TBL_DQ_SYSTEMS' does not exist.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.wrapInSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.ConnectionChild.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.<init>(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement20.<init>(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement30.<init>(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement40.<init>(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement42.<init>(Unknown Source)
	at org.apache.derby.jdbc.Driver42.newEmbedPreparedStatement(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.prepareStatement(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.prepareStatement(Unknown Source)
	at com.jolbox.bonecp.ConnectionHandle.prepareStatement(ConnectionHandle.java:1024)
	at org.openlca.core.database.BaseDao.execute(BaseDao.java:344)
	at org.openlca.core.database.BaseDao.selectAll(BaseDao.java:315)
	at org.openlca.core.database.RootEntityDao.getDescriptors(RootEntityDao.java:68)
	at org.openlca.io.olca.DQSystemImport.run(DQSystemImport.java:29)
	at org.openlca.io.olca.DatabaseImport.importStructs(DatabaseImport.java:78)
	at org.openlca.io.olca.DatabaseImport.run(DatabaseImport.java:34)
	at org.openlca.app.wizards.io.DbImportWizard$ImportDispatch.run(Unknown Source)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
Caused by: java.sql.SQLException: Table/View 'TBL_DQ_SYSTEMS' does not exist.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.wrapArgsForTransportAcrossDRDA(Unknown Source)
	... 23 more
Caused by: ERROR 42X05: Table/View 'TBL_DQ_SYSTEMS' does not exist.
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.impl.sql.compile.FromBaseTable.bindTableDescriptor(Unknown Source)
	at org.apache.derby.impl.sql.compile.FromBaseTable.bindNonVTITables(Unknown Source)
	at org.apache.derby.impl.sql.compile.FromList.bindTables(Unknown Source)
	at org.apache.derby.impl.sql.compile.SelectNode.bindNonVTITables(Unknown Source)
	at org.apache.derby.impl.sql.compile.DMLStatementNode.bindTables(Unknown Source)
	at org.apache.derby.impl.sql.compile.DMLStatementNode.bind(Unknown Source)
	at org.apache.derby.impl.sql.compile.CursorNode.bindStatement(Unknown Source)
	at org.apache.derby.impl.sql.GenericStatement.prepMinion(Unknown Source)
	at org.apache.derby.impl.sql.GenericStatement.prepare(Unknown Source)
	at org.apache.derby.impl.sql.conn.GenericLanguageConnectionContext.prepareInternalStatement(Unknown Source)
	... 17 more
ERROR - failed to import data quality systems
failed to execute query: select id,ref_id,name,description,version,last_change,f_category from tbl_dq_systems
org.openlca.core.database.DatabaseException: failed to execute query: select id,ref_id,name,description,version,last_change,f_category from tbl_dq_systems
	at org.openlca.core.database.DatabaseException.logAndThrow(DatabaseException.java:16)
	at org.openlca.core.database.BaseDao.selectAll(BaseDao.java:319)
	at org.openlca.core.database.RootEntityDao.getDescriptors(RootEntityDao.java:68)
	at org.openlca.io.olca.DQSystemImport.run(DQSystemImport.java:29)
	at org.openlca.io.olca.DatabaseImport.importStructs(DatabaseImport.java:78)
	at org.openlca.io.olca.DatabaseImport.run(DatabaseImport.java:34)
	at org.openlca.app.wizards.io.DbImportWizard$ImportDispatch.run(Unknown Source)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
Caused by: java.sql.SQLSyntaxErrorException: Table/View 'TBL_DQ_SYSTEMS' does not exist.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.getSQLException(Unknown Source)
	...
	at org.apache.derby.impl.jdbc.EmbedConnection.prepareStatement(Unknown Source)
	at com.jolbox.bonecp.ConnectionHandle.prepareStatement(ConnectionHandle.java:1024)
	at org.openlca.core.database.BaseDao.execute(BaseDao.java:344)
	at org.openlca.core.database.BaseDao.selectAll(BaseDao.java:315)
	... 6 more
Caused by: java.sql.SQLException: Table/View 'TBL_DQ_SYSTEMS' does not exist.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.wrapArgsForTransportAcrossDRDA(Unknown Source)
	... 23 more
Caused by: ERROR 42X05: Table/View 'TBL_DQ_SYSTEMS' does not exist.
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	...
	... 17 more
```

**Comment by msrocka** [comment] 2018-06-07 08:33
Closing this issue because this was for openLCA 1.6 and we are now on openLCA 1.7. Also, the problem with the old openLCA LCIA method pack seems to be fixed.

However, there are maybe still issues with database updates, e.g. see [this issue](https://ask.openlca.org/646/importing-old-ecoinvent-database-and-product-systems-failed)
> It seems that something went wrong with the database update. With the restore function (`Navigation > right click > restore database`) you can import the zolca file. When you open the database the update manager should open and you should be able to update the database.

> If the update manager does not open and you still get this error, you can try to force openLCA to re-execute the updates. Therefore, close the database and delete the `_olca_/updates` folder in your database (the database location is `<your user folder>/openLCA-data-1.4/databases/<the database name>`); then, re-open the database. If the update manager does not open you can open it via the main menu `Database > Update manager` and then execute the updates. Before doing this, you should always create a backup of your database (Navigation > Right click > Backup database).

If this does not solve it and there are still update errors, please open a new issue.

**Closed by msrocka** 2018-06-07 08:33 UTC
Labels: bug
