### ISSUE TITLE
question

### ISSUE THREAD

**Issue by iamlinguo** [GreenDelta/olca-app#345] opened 2023-08-10 10:22 UTC
Git push exception 'Caused by: org. eclipse. jgit. errors. TransportException: http://localhost:8080/admin/test: Authentication not supported

” What could be the problem?

**Comment by Leeeks** [comment] 2023-08-15 07:21
Hello,
i have the same Problem. Setup and connection to the 2.0 Collaboration Server went seamless. Git push doesn't work for me though.
![Repo Connection](https://github.com/GreenDelta/olca-app/assets/47191992/e9cba9c0-51d7-45fd-b173-e999e0d83407)
![Error](https://github.com/GreenDelta/olca-app/assets/47191992/956a7a7e-78a7-4639-9d2f-e5b26548c179)
![Error2](https://github.com/GreenDelta/olca-app/assets/47191992/e82cf253-088c-432e-8da6-0812a46de52c)

**Comment by SebastianGreve-GreenDelta** [comment] 2023-08-15 10:16
You are using the same credentials, with which you can login to the web interface?

**Comment by Leeeks** [comment] 2023-08-15 10:38
Yes, exactly. The Login in the Webinterface works fine for Admin as well as
for the user i created.

Sebastian Greve ***@***.***> schrieb am Di., 15. Aug. 2023,
12:16:

**Comment by SebastianGreve-GreenDelta** [comment] 2023-08-15 12:18
Did you install Java JDK or JRE? I found an issue with JGit authentication when using the JRE

**Comment by Leeeks** [comment] 2023-08-15 12:23
this is the java version running on the system:
![image](https://github.com/GreenDelta/olca-app/assets/47191992/15999d29-83d0-444c-80ba-056f170f0f6d)

**Comment by SebastianGreve-GreenDelta** [comment] 2023-08-15 13:19
I have installed the same java version, this should not be the issue. Are you behind a firewall or proxy? I can't reproduce the problem

**Comment by Leeeks** [comment] 2023-08-15 14:09
Definitely no proxy. I also deactivated https and used the Linux Server machine to run the OpenLCA client to make sure, that the firewall is not the problem. I connected to the localhost succesfully:
![Error Localhost](https://github.com/GreenDelta/olca-app/assets/47191992/53207406-2cd9-495f-b618-ee13e889eeaf)

I get the same error though:
![Localhost Error](https://github.com/GreenDelta/olca-app/assets/47191992/5a98c04d-0aaa-4052-9b72-5fc55b69f56d)

Here is the according log text:
![Error3](https://github.com/GreenDelta/olca-app/assets/47191992/f0e40aa8-54ee-423c-9a8d-28f6a30e9703)

**Comment by SebastianGreve-GreenDelta** [comment] 2023-08-15 15:53
FYI Leeeks was able to push to a different server with the same client. So it seems to be something related to the server setup.
The working server is an Ubuntu 22 with openjdk 17.0.8 installed. Maybe that helps for further analysis

**Comment by SebastianGreve-GreenDelta** [comment] 2023-08-16 08:38
The problem occurs with the admin user only it seems, we are working on a fix for this, but it seems you can avoid the issue by creating a another user and create repositories and push with this user

**Comment by SebastianGreve-GreenDelta** [comment] 2023-08-16 10:18
The problem is related to a change in reserved names, which was not reflected in the installer. The name 'admin' is not allowed anymore. I updated the installer on the openLCA website. If you want to fix it in your running server, create a new a different admin user e.g. administrator and delete the admin user.

**Closed by SebastianGreve-GreenDelta** 2023-08-16 10:18 UTC
