### ISSUE TITLE
Crash when viewing "locations" after "calculate" on product system

### ISSUE THREAD

**Issue by cazgp** [GreenDelta/olca-app#9] opened 2015-09-02 01:25 UTC
```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007fbf386c34cf, pid=19932, tid=140459264104192
#
# JRE version: Java(TM) SE Runtime Environment (8.0_05-b13) (build 1.8.0_05-b13)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.5-b02 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# C  [ld-linux-x86-64.so.2+0xc4cf]  _dl_rtld_di_serinfo+0x2dbf
#
# Core dump written. Default location: /home/user/Downloads/openLCA/core or core.19932
#
# An error report file with more information is saved as:
# /home/user/Downloads/openLCA/hs_err_pid19932.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.sun.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
```

Is there somewhere to upload a core dump?

Running elementary luna (Ubuntu 14.04).

**Comment by msrocka** [comment] 2016-10-31 15:18
I think that this is a duplicate of issue #4. So I closed this one.

**Closed by msrocka** 2016-10-31 15:18 UTC
