### ISSUE TITLE
OLCA 2.0 "is damaged" on MacOS

### ISSUE THREAD

**Issue by NansD** [GreenDelta/olca-app#264] opened 2022-11-22 16:06 UTC
Hi ! Thanks for OLCA 2.0.
However I'm facing this issue :
<img width="372" alt="image" src="https://user-images.githubusercontent.com/18481465/203362882-a3dc8569-38cd-4cd1-9f07-179bf5a8995c.png">

**Comment by msrocka** [comment] 2022-11-22 16:15
This is a duplicate of this issue: https://github.com/GreenDelta/olca-app/issues/152

**Closed by msrocka** 2022-11-22 16:15 UTC
Labels: duplicate
